version: '3'
services:
    mssql:
        build:
            context: ./
            dockerfile: "Dockerfile"
        container_name: mssql-server
        ports:
          - 1433:1433
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=MssqlPass123
          - MSSQL_PID=Express
          - MSSQL_LCID=1041
          - MSSQL_COLLATION=Japanese_CI_AS