version: '3'
services:
    mssql:
      image: microsoft/mssql-server-linux:latest
      container_name: mssql-server
      ports:
        - 1433:1433
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=1L)|q'#G
        - MSSQL_PID=Express
        - MSSQL_LCID=1041
        - MSSQL_COLLATION=Japanese_CI_AS